### ISSUE TITLE
RangeError: Invalid string length

### ISSUE THREAD

**Issue by jiatern** [kinchanmaemo/standalone-html#4]
Hi, first of all thanks for making this tool, I have been using for some time and it is really useful.

I recently have a page that I tried to convert but I get the following error. It is actually a html file of discord chat exports (exported using https://github.com/Tyrrrz/DiscordChatExporter) but weirdly, this error never happened to other exports that I've done but only this particular one.

(e.g. I tried to export a chat from another time frame and no error is found when converting using standalone-html)

I have the same issue on my windows machine and ubuntu VPS.

Is there something that I can do about it? Thanks in advance.

``` 
C:\Users\jiate\AppData\Roaming\npm\node_modules\standalone-html\node_modules\dom-serializer\index.js:83
      output += renderTag(elem, opts);
                ^

RangeError: Invalid string length
    at module.exports (C:\Users\jiate\AppData\Roaming\npm\node_modules\standalone-html\node_modules\dom-serializer\index.js:83:17)
    at renderTag (C:\Users\jiate\AppData\Roaming\npm\node_modules\standalone-html\node_modules\dom-serializer\index.js:116:14)
    at module.exports (C:\Users\jiate\AppData\Roaming\npm\node_modules\standalone-html\node_modules\dom-serializer\index.js:83:17)
    at renderTag (C:\Users\jiate\AppData\Roaming\npm\node_modules\standalone-html\node_modules\dom-serializer\index.js:116:14)
    at module.exports (C:\Users\jiate\AppData\Roaming\npm\node_modules\standalone-html\node_modules\dom-serializer\index.js:83:17)
    at renderTag (C:\Users\jiate\AppData\Roaming\npm\node_modules\standalone-html\node_modules\dom-serializer\index.js:116:14)
    at module.exports (C:\Users\jiate\AppData\Roaming\npm\node_modules\standalone-html\node_modules\dom-serializer\index.js:83:17)
    at render (C:\Users\jiate\AppData\Roaming\npm\node_modules\standalone-html\node_modules\cheerio\lib\static.js:70:10)    at Function.exports.html (C:\Users\jiate\AppData\Roaming\npm\node_modules\standalone-html\node_modules\cheerio\lib\static.js:94:10)
    at Object.module.exports.cli (C:\Users\jiate\AppData\Roaming\npm\node_modules\standalone-html\standalone-html.js:97:11)
    at startApp (C:\Users\jiate\AppData\Roaming\npm\node_modules\standalone-html\bin\standalone-html.js:67:14)
    at C:\Users\jiate\AppData\Roaming\npm\node_modules\standalone-html\bin\standalone-html.js:47:4
    at FSReqCallback.oncomplete (node:fs:199:5)
```

**Comment by kinchanmaemo** [comment]
Hi and thank you! 
I installed DiscordChatExporter to try to reproduce this bug. But I didn't get the same error. Can you put an example of the html code that returns this error?

**Comment by jiatern** [comment]
Hi, for some reasons I can't replicate this as well, it seems to only affect certain messages that I cannot identify.

Also, I think it is an issue only occurring to DiscordChatExporter files so I think it's not fair for you to troubleshoot it - I reverted to the older version of DiscordChatExporter  because the newer version exports even .woff font files, .css and .js files which makes the standalone HTML file extremely huge.

Maybe those files made the conversion difficult.

Thank you so much!

**Comment by kinchanmaemo** [comment]
you're welcome! Remote files are normally not a problem but it might be a good idea to add remote resource download as an option. That might help.  If the error is random, I close this issue for now. Feel free to reopen it if needed.
